# Generated by Django 5.0.6 on 2024-06-07 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True, null=True)),
                ('email', models.CharField(max_length=200)),
                ('done', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
