# Generated by Django 5.0.6 on 2024-06-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_contactus_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อผู้ถาม (name)')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่อปัญหา (title)')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='รายละเอียดปัญหา (detail)')),
                ('email', models.CharField(max_length=200, verbose_name='อีเมลผู้ติดต่อ (email)')),
                ('done', models.BooleanField(default=False, verbose_name='แก้ปัญหาจบแล้วยัง? (done)')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='สรุปว่าปัญหานี้แก้อย่างไร (summary)')),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
